spring:
  application:
    name: spring-ai-functions
  #Pass API key as environment variable, e.g. -DOPENAI_API_KEY=your-api-key
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo
sfg:
  aiapp:
    apiNinjasKey: ${API_NINJAS_KEY}
